type NavEntry = readonly [string, string] | readonly [string, string, readonly (readonly [string, string])[]];

export default {
  "Getting Started": [
    ["What is ApiHug?", "/docs/start/what-is-apihug"],
    ["Quick Start", "/docs/start"],
  ] as NavEntry[],
  Editor: [
    ["Editor Intro", "/docs/idea"],
    ["FAQ", "/docs/idea/faq"],
    ["Shortcut", "/docs/idea/000-shortcut"],
    ["Install Plugin", "/docs/idea/001-install-plugin"],
    ["Start Project", "/docs/idea/002-start-project"],
    ["Tool Window", "/docs/idea/003-tool-window"],
    ["Service", "/docs/idea/004-service-api-collection"],
    ["API", "/docs/idea/005-api-detail"],
    ["Component", "/docs/idea/006-components"],
    ["Constant", "/docs/idea/007-constants"],
    ["Error", "/docs/idea/008-errors"],
    ["Entity", "/docs/idea/009-entity"],
    ["Stub", "/docs/idea/010-stub"],
    ["Test", "/docs/idea/011-test"],
    ["Settings Server", "/docs/idea/012-settings-server"],
    ["Settings Export", "/docs/idea/013-settings-export"],
    ["Settings Knowledge", "/docs/idea/014-settings-knowledge"],
    ["Editor", "/docs/idea/015-editor"],
  ] as NavEntry[],
  "Protocol Buffers": [
    ["Proto Intro", "/docs/protobuf"],
    ["Protobuf & OAS", "/docs/protobuf/proto-oas"],
    ["Protobuf Option", "/docs/protobuf/proto-option"],
    ["Protobuf Entity", "/docs/protobuf/proto-entity"],
  ] as NavEntry[],
  Framework: [
    ["Framework Intro", "/docs/framework"],
    ["Spring Common", "/docs/framework/spring-common"],
    ["Spring Core", "/docs/framework/spring-core"],
    ["Spring Cache", "/docs/framework/spring-cache"],
    ["Spring API", "/docs/framework/spring-api"],
    ["Spring Data", "/docs/framework/spring-data"],
    ["Spring Security", "/docs/framework/spring-security"],
    ["Spring Mock", "/docs/framework/spring-mock"],
    ["All About Contract", "/docs/framework/all-about-contract"],
    ["Basic Authority", "/docs/framework/widget/authority"],
  ] as NavEntry[],
  Kola: [
    ["Intro", "/docs/kola"],
    ["What is Kola", "/docs/kola/001_what_is_kola"],
    ["Design of Kola", "/docs/kola/002_design_of_kola"],
    ["Kola Contract", "/docs/kola/003_dsl_contract"],
    ["Kola Principle", "/docs/kola/004_principle"],
    ["Tool Chain", "/docs/kola/005_tool_chain"],
  ] as NavEntry[],
  "Tool Chain": [
    ["Intro", "/docs/tool"],
    ["BMAD", "/docs/tool/apihug-bmad"],
    ["REPL", "/docs/tool/apihug-repl"],
    ["Lint", "/docs/tool/apihug-lint"],
    ["Wire", "/docs/tool/gradle-wire"],
    ["Stub", "/docs/tool/gradle-stub"],
  ] as NavEntry[],
  Copilot: [
    ["Intro", "/docs/copilot"],
    ["Settings", "/docs/copilot/001_settings"],
    ["Functions", "/docs/copilot/002_functions"],
  ] as NavEntry[],
  MCP: [["Intro", "/docs/mcp/001_start"]] as NavEntry[],
  Spec: [
    ["Vibe", "/docs/spec"],
    ["API", "/docs/spec/swagger"],
    ["Domain", "/docs/spec/domain"],
    ["Constant", "/docs/spec/constant"],
    ["Mock", "/docs/spec/mock"],
    ["Version", "/docs/spec/version"],
  ] as NavEntry[],
  UI: [
    ["Intro", "/docs/ui"],
    ["Proto", "/docs/ui/001_proto"],
    ["Vue", "/docs/ui/002_vue"],
    ["App", "/docs/ui/003_app"],
    ["Tool", "/docs/ui/004_tool_chain"],
  ] as NavEntry[],
  "How-To": [
    ["Upload File", "/docs/how/001_support_upload_file"],
    ["Update Header & Cookie", "/docs/how/002_update_header_cookie"],
    ["How to Use Enum", "/docs/how/003_how_to_handle_enum"],
    ["Define API Root Path", "/docs/how/004_how_define_api_root_path"],
    ["Useful Mini Plugins", "/docs/how/005_helpful_inner_plugin"],
    ["Max/Min Length Items", "/docs/how/006_understand_max_min_length_items_properties"],
  ] as NavEntry[],
  Milestone: [
    ["Index", "/docs/milestone"],
    ["Milestone-1.0.0", "/docs/milestone/milestone-1.0.0-RELEASE"],
    ["Milestone-2.0.0", "/docs/milestone/milestone-2.0.0-RELEASE"],
    ["Upgrade-20250515", "/docs/milestone/upgrade-1.3.8-RELEASE"],
    ["Milestone-20240510", "/docs/milestone/milestone-20240510"],
    ["Milestone-20240222", "/docs/milestone/milestone-20240222"],
  ] as NavEntry[],
  Changelog: [
    ["Index", "/docs/changelog"],
    ["SDK", "/docs/changelog/sdk"],
    ["SDK 0.8.6", "/docs/changelog/detail/SDK_0.8.6"],
    ["SDK 0.7.8", "/docs/changelog/detail/SDK_0.7.8"],
    ["Plugin", "/docs/changelog/plugin"],
  ] as NavEntry[],
  "Core Principles": [
    ["Empathy is Important", "/docs/principles/empathy-is-important"],
    ["Common Language", "/docs/principles/common-language"],
    ["Single Source Of Truth", "/docs/principles/single-source-of-truth"],
    ["Leverage & Integration", "/docs/principles/leverage-integration"],
  ] as NavEntry[],
};
