export const documentationNav = {
  'Getting Started': [
    {
      title: 'Intro',
      href: '/docs/start/what-is-apihug',
    },
    {
      title: 'Quick start',
      href: '/docs/start',
    },
  ],
  "Editor": [
    {title: 'Editor Intro', href: '/docs/idea',},
    {title: 'FAQ', href: '/docs/idea/faq',},
    {title: 'Shortcut', href: '/docs/idea/000-shortcut',},
    {title: 'Install Plugin', href: '/docs/idea/001-install-plugin',},
    {title: 'Start Project', href: '/docs/idea/002-start-project',},
    {title: 'Tool Window', href: '/docs/idea/003-tool-window',},
    {title: 'Service', href: '/docs/idea/004-service-api-collection',},
    {title: 'Api', href: '/docs/idea/005-api-detail',},
    {title: 'Component', href: '/docs/idea/006-components',},
    {title: 'Constant', href: '/docs/idea/007-constants',},
    {title: 'Error', href: '/docs/idea/008-errors',},
    {title: 'Entity', href: '/docs/idea/009-entity',},
    {title: 'Stub', href: '/docs/idea/010-stub',},
    {title: 'Test', href: '/docs/idea/011-test',},
    {title: 'Settings Server', href: '/docs/idea/012-settings-server',},
    {title: 'Settings Export', href: '/docs/idea/013-settings-export',},
    {title: 'Settings Knowledge', href: '/docs/idea/014-settings-knowledge',},
    {title: 'Editor', href: '/docs/idea/015-editor',},
  ],
  "Protocol Buffers": [
    {title: 'Proto Intro', href: '/docs/protobuf'},
    {title: 'Protobuf & OAS', href: '/docs/protobuf/proto-oas'},
    {title: 'Protobuf Option', href: '/docs/protobuf/proto-option'},
    {title: 'Protobuf Entity', href: '/docs/protobuf/proto-entity'},
  ],
  "Framework": [
    {title: 'Framework Intro', href: '/docs/framework'},
    {title: 'Spring Common', href: '/docs/framework/spring-common'},
    {title: 'Spring Core', href: '/docs/framework/spring-core'},
    {title: 'Spring Cache', href: '/docs/framework/spring-cache'},
    {title: 'Spring API', href: '/docs/framework/spring-api'},
    {title: 'Spring Data', href: '/docs/framework/spring-data'},
    {title: 'Spring Security', href: '/docs/framework/spring-security'},
    {title: 'Spring Mock', href: '/docs/framework/spring-mock'},
    {title: 'Basic Authority', href: '/docs/framework/widget/authority'},
  ],
  "Kola": [
    {title: 'Intro', href: '/docs/kola'},
    {title: 'What is Kola', href: '/docs/kola/001_what_is_kola'},
    {title: 'Design of Kola', href: '/docs/kola/002_design_of_kola'},
    {title: 'Kola Contract', href: '/docs/kola/003_dsl_contract'},
    {title: 'Kola Principle', href: '/docs/kola/004_principle'},
    {title: 'Tool Chain', href: '/docs/kola/005_tool_chain'},
  ],
  "Tool Chain": [
    {title: 'Intro', href: '/docs/tool'},
    {title: 'Lint', href: '/docs/tool/apihug-lint'},
    {title: 'Wire', href: '/docs/tool/gradle-wire'},
    {title: 'Stub', href: '/docs/tool/gradle-stub'},
  ],
  "Copilot": [
    {title: 'Intro', href: '/docs/copilot'},
    {title: 'Settings', href: '/docs/copilot/001_settings'},
    {title: 'Functions', href: '/docs/copilot/002_functions'},
  ],
  "MCP": [
    {title: 'Intro', href: '/docs/mcp/001_start'},
  ],
  "UI": [
    {title: 'Intro', href: '/docs/ui'},
    {title: 'Proto', href: '/docs/ui/001_proto'},
    {title: 'Vue', href: '/docs/ui/002_vue'},
    {title: 'App', href: '/docs/ui/003_app'},
    {title: 'Tool', href: '/docs/ui/004_tool_chain'},
  ],
  "How": [
    {title: 'Upload File', href: '/docs/how/001_support_upload_file'},
    {title: 'Update Header & Cookie', href: '/docs/how/002_update_header_cookie'},
    {title: 'How to use Enum', href: '/docs/how/003_how_to_handle_enum'},
    {title: 'How to define api root path', href: '/docs/how/004_how_define_api_root_path'},
    {title: 'Useful Built-in Mini Plugins', href: '/docs/how/005_helpful_inner_plugin'},
    {title: 'How to use the max/min length items', href: '/docs/how/006_understand_max_min_length_items_properties'},
  ],
  Milestone:[
    {title: 'Index', href: '/docs/milestone'},
    {title: 'Upgrade-20250515', href: '/docs/milestone/upgrade-1.3.8-RELEASE'},
    {title: 'Milestone-20240510', href: '/docs/milestone/milestone-20240510'},
    {title: 'Milestone-20240222', href: '/docs/milestone/milestone-20240222'},
  ],
  "ChangeLog":[
    {title: 'Index', href: '/docs/changelog'},
    {title: 'SDK', href: '/docs/changelog/sdk'},
    {title: 'Plugin', href: '/docs/changelog/plugin'},
  ],
  'Core Principles': [
    {title: 'Empathy is Important', href: '/docs/principles/empathy-is-important',},
    {title: 'Common Language', href: '/docs/principles/common-language',},
    {title: 'Single Source Of Truth', href: '/docs/principles/single-source-of-truth',},
    {title: 'Leverage & Integration', href: '/docs/principles/leverage-integration',}
  ]
}
