export const documentationNav = {
  'Getting Started': [
    {
      title: '介绍',
      href: '/zhCN-docs/start/what-is-apihug',
    },
    {
      title: '快速启动',
      href: '/zhCN-docs/start',
    },
  ],
  "Editor": [
    {title: '插件介绍', href: '/zhCN-docs/idea',},
    {title: 'FAQ', href: '/zhCN-docs/idea/faq',},
    {title: '快捷键', href: '/zhCN-docs/idea/000-shortcut',},
    {title: '安装插件', href: '/zhCN-docs/idea/001-install-plugin',},
    {title: '开启项目', href: '/zhCN-docs/idea/002-start-project',},
    {title: '工具窗口', href: '/zhCN-docs/idea/003-tool-window',},
    {title: '服务', href: '/zhCN-docs/idea/004-service-api-collection',},
    {title: 'Api', href: '/zhCN-docs/idea/005-api-detail',},
    {title: '组件', href: '/zhCN-docs/idea/006-components',},
    {title: '常量', href: '/zhCN-docs/idea/007-constants',},
    {title: '错误', href: '/zhCN-docs/idea/008-errors',},
    {title: '实体', href: '/zhCN-docs/idea/009-entity',},
    {title: 'Stub', href: '/zhCN-docs/idea/010-stub',},
    {title: '测试', href: '/zhCN-docs/idea/011-test',},
    {title: '服务配置', href: '/zhCN-docs/idea/012-settings-server',},
    {title: '导出配置', href: '/zhCN-docs/idea/013-settings-export',},
    {title: '知识库配置', href: '/zhCN-docs/idea/014-settings-knowledge',},
    {title: '编辑', href: '/zhCN-docs/idea/015-editor',},
  ],
  "Protocol Buffers": [
    {title: 'Proto 介绍', href: '/zhCN-docs/protobuf'},
    {title: 'Protobuf & OAS', href: '/zhCN-docs/protobuf/proto-oas'},
    {title: 'Protobuf Option', href: '/zhCN-docs/protobuf/proto-option'},
    {title: 'Protobuf Entity', href: '/zhCN-docs/protobuf/proto-entity'},
  ],
  "Framework": [
    {title: '框架介绍', href: '/zhCN-docs/framework'},
    {title: 'Spring 公用库', href: '/zhCN-docs/framework/spring-common'},
    {title: 'Spring 核心库', href: '/zhCN-docs/framework/spring-core'},
    {title: 'Spring 缓存库', href: '/zhCN-docs/framework/spring-cache'},
    {title: 'Spring API库', href: '/zhCN-docs/framework/spring-api'},
    {title: 'Spring 数据库', href: '/zhCN-docs/framework/spring-data'},
    {title: 'Spring 安全库', href: '/zhCN-docs/framework/spring-security'},
    {title: 'Spring Mock库', href: '/zhCN-docs/framework/spring-mock'},
    {title: '关于合约 Contract', href: '/zhCN-docs/framework/all-about-contract'},
    {title: 'Spring 极简RBAC', href: '/zhCN-docs/framework/widget/authority'},
  ],
  "Kola": [
    {title: '介绍', href: '/zhCN-docs/kola'},
    {title: 'Kola 是什么', href: '/zhCN-docs/kola/001_what_is_kola'},
    {title: 'Kola 设计', href: '/zhCN-docs/kola/002_design_of_kola'},
    {title: 'Kola 协议', href: '/zhCN-docs/kola/003_dsl_contract'},
    {title: 'Kola 原则', href: '/zhCN-docs/kola/004_principle'},
    {title: '工具链', href: '/zhCN-docs/kola/005_tool_chain'},
  ],
  "Tool Chain": [
    {title: '介绍', href: '/zhCN-docs/tool'},
    {title: 'REPL', href: '/zhCN-docs/tool/apihug-repl'},
    {title: 'BMAD', href: '/zhCN-docs/tool/apihug-bmad'},
    {title: 'Lint', href: '/zhCN-docs/tool/apihug-lint'},
    {title: 'Wire', href: '/zhCN-docs/tool/gradle-wire'},
    {title: 'Stub', href: '/zhCN-docs/tool/gradle-stub'},
  ],
  "Copilot": [
    {title: '介绍', href: '/zhCN-docs/copilot'},
    {title: '配置', href: '/zhCN-docs/copilot/001_settings'},
    {title: '功能', href: '/zhCN-docs/copilot/002_functions'},
  ],
  "MCP": [
    {title: '介绍', href: '/zhCN-docs/mcp/001_start'},
  ],
  "Spec": [
    {title: 'Vibe', href: '/zhCN-docs/spec'},
    {title: 'API', href: '/zhCN-docs/spec/swagger'},
    {title: 'Domain', href: '/zhCN-docs/spec/domain'},
    {title: 'Constant', href: '/zhCN-docs/spec/constant'},
  ],
  "UI": [
    {title: '介绍', href: '/zhCN-docs/ui'},
    {title: '协议', href: '/zhCN-docs/ui/001_proto'},
    {title: 'Vue', href: '/zhCN-docs/ui/002_vue'},
    {title: '应用', href: '/zhCN-docs/ui/003_app'},
    {title: '工具链', href: '/zhCN-docs/ui/004_tool_chain'},
  ],
  "How": [
    {title: '文件上传', href: '/zhCN-docs/how/001_support_upload_file'},
    {title: '更新 Header & Cookie', href: '/zhCN-docs/how/002_update_header_cookie'},
    {title: '如何使用 Enum', href: '/zhCN-docs/how/003_how_to_handle_enum'},
    {title: '如何定义api根目录', href: '/zhCN-docs/how/004_how_define_api_root_path'},
    {title: '有用内置小插件', href: '/zhCN-docs/how/005_helpful_inner_plugin'},
    {title: '如何用好max/min length items', href: '/zhCN-docs/how/006_understand_max_min_length_items_properties'},
  ],
  Milestone: [
    {title: 'Index', href: '/zhCN-docs/milestone'},
    {title: '里程碑-2.0.0', href: '/zhCN-docs/milestone/milestone-2.0.0-RELEASE'},
    {title: 'Upgrade-20250515', href: '/zhCN-docs/milestone/upgrade-1.3.8-RELEASE'},
    {title: '里程碑-20240510', href: '/zhCN-docs/milestone/milestone-20240510'},
    {title: '里程碑-20240222', href: '/zhCN-docs/milestone/milestone-20240222'},
  ],
  "ChangeLog": [
    {title: 'Index', href: '/zhCN-docs/changelog'},
    {title: 'SDK', href: '/zhCN-docs/changelog/sdk'},
    {title: 'Plugin', href: '/zhCN-docs/changelog/plugin'},
  ],
  'Core Principles': [
    {title: '同理心很重要', href: '/zhCN-docs/principles/empathy-is-important',},
    {title: '共同语言', href: '/zhCN-docs/principles/common-language',},
    {title: '单一信任源', href: '/zhCN-docs/principles/single-source-of-truth',},
    {title: '集成和开放', href: '/zhCN-docs/principles/leverage-integration',}
  ]
}
