type NavEntry = readonly [string, string] | readonly [string, string, readonly (readonly [string, string])[]];

export default {
  "Getting Started": [
    ["介绍", "/zhCN-docs/start/what-is-apihug"],
    ["快速开启", "/zhCN-docs/start"],
  ] as NavEntry[],
  Editor: [
    ["插件介绍", "/zhCN-docs/idea"],
    ["FAQ", "/zhCN-docs/idea/faq"],
    ["快捷键", "/zhCN-docs/idea/000-shortcut"],
    ["安装插件", "/zhCN-docs/idea/001-install-plugin"],
    ["开启项目", "/zhCN-docs/idea/002-start-project"],
    ["工具窗口", "/zhCN-docs/idea/003-tool-window"],
    ["服务", "/zhCN-docs/idea/004-service-api-collection"],
    ["Api", "/zhCN-docs/idea/005-api-detail"],
    ["组件", "/zhCN-docs/idea/006-components"],
    ["常量", "/zhCN-docs/idea/007-constants"],
    ["错误", "/zhCN-docs/idea/008-errors"],
    ["实体", "/zhCN-docs/idea/009-entity"],
    ["Stub", "/zhCN-docs/idea/010-stub"],
    ["测试", "/zhCN-docs/idea/011-test"],
    ["服务配置", "/zhCN-docs/idea/012-settings-server"],
    ["导出配置", "/zhCN-docs/idea/013-settings-export"],
    ["知识库配置", "/zhCN-docs/idea/014-settings-knowledge"],
    ["编辑", "/zhCN-docs/idea/015-editor"],
  ] as NavEntry[],
  "Protocol Buffers": [
    ["Proto 介绍", "/zhCN-docs/protobuf"],
    ["Protobuf & OAS", "/zhCN-docs/protobuf/proto-oas"],
    ["Protobuf Option", "/zhCN-docs/protobuf/proto-option"],
    ["Protobuf Entity", "/zhCN-docs/protobuf/proto-entity"],
  ] as NavEntry[],
  Framework: [
    ["框架介绍", "/zhCN-docs/framework"],
    ["Spring 公用库", "/zhCN-docs/framework/spring-common"],
    ["Spring 核心库", "/zhCN-docs/framework/spring-core"],
    ["Spring 缓存库", "/zhCN-docs/framework/spring-cache"],
    ["Spring API库", "/zhCN-docs/framework/spring-api"],
    ["Spring 数据库", "/zhCN-docs/framework/spring-data"],
    ["Spring 安全库", "/zhCN-docs/framework/spring-security"],
    ["Spring Mock库", "/zhCN-docs/framework/spring-mock"],
    ["关于合约 Contract", "/zhCN-docs/framework/all-about-contract"],
    ["Spring 极简RBAC", "/zhCN-docs/framework/widget/authority"],
  ] as NavEntry[],
  Kola: [
    ["介绍", "/zhCN-docs/kola"],
    ["Kola 是什么", "/zhCN-docs/kola/001_what_is_kola"],
    ["Kola 设计", "/zhCN-docs/kola/002_design_of_kola"],
    ["Kola 协议", "/zhCN-docs/kola/003_dsl_contract"],
    ["Kola 原则", "/zhCN-docs/kola/004_principle"],
    ["工具链", "/zhCN-docs/kola/005_tool_chain"],
    ["配置与附录", "/zhCN-docs/kola/006_configurations"],
  ] as NavEntry[],
  "Tool Chain": [
    ["介绍", "/zhCN-docs/tool"],
    ["REPL", "/zhCN-docs/tool/apihug-repl"],
    ["BMAD", "/zhCN-docs/tool/apihug-bmad"],
    ["Lint", "/zhCN-docs/tool/apihug-lint"],
    ["Wire", "/zhCN-docs/tool/gradle-wire"],
    ["Stub", "/zhCN-docs/tool/gradle-stub"],
  ] as NavEntry[],
  Copilot: [
    ["介绍", "/zhCN-docs/copilot"],
    ["配置", "/zhCN-docs/copilot/001_settings"],
    ["功能", "/zhCN-docs/copilot/002_functions"],
  ] as NavEntry[],
  MCP: [["介绍", "/zhCN-docs/mcp/001_start"]] as NavEntry[],
  Spec: [
    ["Vibe", "/zhCN-docs/spec"],
    ["API", "/zhCN-docs/spec/swagger"],
    ["Domain", "/zhCN-docs/spec/domain"],
    ["Constant", "/zhCN-docs/spec/constant"],
  ] as NavEntry[],
  UI: [
    ["介绍", "/zhCN-docs/ui"],
    ["协议", "/zhCN-docs/ui/001_proto"],
    ["Vue", "/zhCN-docs/ui/002_vue"],
    ["应用", "/zhCN-docs/ui/003_app"],
    ["工具链", "/zhCN-docs/ui/004_tool_chain"],
  ] as NavEntry[],
  How: [
    ["文件上传", "/zhCN-docs/how/001_support_upload_file"],
    ["更新 Header & Cookie", "/zhCN-docs/how/002_update_header_cookie"],
    ["如何使用 Enum", "/zhCN-docs/how/003_how_to_handle_enum"],
    ["如何定义api根目录", "/zhCN-docs/how/004_how_define_api_root_path"],
    ["有用内置小插件", "/zhCN-docs/how/005_helpful_inner_plugin"],
    ["如何用好max/min length items", "/zhCN-docs/how/006_understand_max_min_length_items_properties"],
  ] as NavEntry[],
  Milestone: [
    ["Index", "/zhCN-docs/milestone"],
    ["Milestone-1.0.0", "/zhCN-docs/milestone/milestone-1.0.0-RELEASE"],
    ["里程碑-2.0.0", "/zhCN-docs/milestone/milestone-2.0.0-RELEASE"],
    ["Upgrade-20250515", "/zhCN-docs/milestone/upgrade-1.3.8-RELEASE"],
    ["里程碑-20240510", "/zhCN-docs/milestone/milestone-20240510"],
    ["里程碑-20240222", "/zhCN-docs/milestone/milestone-20240222"],
  ] as NavEntry[],
  ChangeLog: [
    ["Index", "/zhCN-docs/changelog"],
    ["SDK", "/zhCN-docs/changelog/sdk"],
    ["SDK 0.7.8", "/zhCN-docs/changelog/detail/SDK_0.7.8"],
    ["SDK 0.7.8 中文", "/zhCN-docs/changelog/detail/SDK_0.7.8_cn"],
    ["SDK 0.8.6", "/zhCN-docs/changelog/detail/SDK_0.8.6"],
    ["SDK 0.8.6 中文", "/zhCN-docs/changelog/detail/SDK_0.8.6_cn"],
    ["Plugin", "/zhCN-docs/changelog/plugin"],
  ] as NavEntry[],
  "Core Principles": [
    ["同理心很重要", "/zhCN-docs/principles/empathy-is-important"],
    ["共同语言", "/zhCN-docs/principles/common-language"],
    ["单一信任源", "/zhCN-docs/principles/single-source-of-truth"],
    ["集成和开放", "/zhCN-docs/principles/leverage-integration"],
  ] as NavEntry[],
};
