type NavEntry = readonly [string, string] | readonly [string, string, readonly (readonly [string, string])[]];

export default {
  "快速开始": [
    ["介绍", "/zhCN-docs/start/what-is-apihug"],
    ["快速开始", "/zhCN-docs/start"],
  ] as NavEntry[],
  "技能与规则": [
    ["概览", "/zhCN-docs/skills"],
    ["规则", "/zhCN-docs/skills/rules"],
    ["工作流", "/zhCN-docs/skills/workflow"],
    ["Create Story", "/zhCN-docs/skills/create-story"],
    ["Dev Story", "/zhCN-docs/skills/dev-story"],
    ["Proto Review", "/zhCN-docs/skills/proto-review"],
    ["Implementation Review", "/zhCN-docs/skills/impl-review"],
  ] as NavEntry[],
  Copilot: [
    ["介绍", "/zhCN-docs/copilot"],
    ["设置", "/zhCN-docs/copilot/001_settings"],
    ["功能", "/zhCN-docs/copilot/002_functions"],
  ] as NavEntry[],
  MCP: [["介绍", "/zhCN-docs/mcp/001_start"]] as NavEntry[],
  "工具链": [
    ["介绍", "/zhCN-docs/tool"],
    ["REPL", "/zhCN-docs/tool/apihug-repl"],
    ["BMAD", "/zhCN-docs/tool/apihug-bmad"],
    ["Lint", "/zhCN-docs/tool/apihug-lint"],
    ["Wire", "/zhCN-docs/tool/gradle-wire"],
    ["Stub", "/zhCN-docs/tool/gradle-stub"],
  ] as NavEntry[],
  "Protocol Buffers": [
    ["Proto 介绍", "/zhCN-docs/protobuf"],
    ["Protobuf 与 OAS", "/zhCN-docs/protobuf/proto-oas"],
    ["Protobuf 选项", "/zhCN-docs/protobuf/proto-option"],
    ["Protobuf 实体", "/zhCN-docs/protobuf/proto-entity"],
  ] as NavEntry[],
  "框架": [
    ["框架介绍", "/zhCN-docs/framework"],
    ["Spring 公共库", "/zhCN-docs/framework/spring-common"],
    ["Spring 核心库", "/zhCN-docs/framework/spring-core"],
    ["Spring 缓存库", "/zhCN-docs/framework/spring-cache"],
    ["Spring API 库", "/zhCN-docs/framework/spring-api"],
    ["Spring 数据库支持", "/zhCN-docs/framework/spring-data"],
    ["Spring 安全库", "/zhCN-docs/framework/spring-security"],
    ["Spring Mock 库", "/zhCN-docs/framework/spring-mock"],
    ["关于契约 Contract", "/zhCN-docs/framework/all-about-contract"],
    ["基础权限", "/zhCN-docs/framework/widget/authority"],
  ] as NavEntry[],
  "规范": [
    ["Vibe", "/zhCN-docs/spec"],
    ["API", "/zhCN-docs/spec/swagger"],
    ["Mock", "/zhCN-docs/spec/mock"],
    ["Domain", "/zhCN-docs/spec/domain"],
    ["Constant", "/zhCN-docs/spec/constant"],
    ["Version", "/zhCN-docs/spec/version"],
  ] as NavEntry[],
  UI: [
    ["介绍", "/zhCN-docs/ui"],
    ["协议", "/zhCN-docs/ui/001_proto"],
    ["Vue", "/zhCN-docs/ui/002_vue"],
    ["应用", "/zhCN-docs/ui/003_app"],
    ["工具链", "/zhCN-docs/ui/004_tool_chain"],
  ] as NavEntry[],
  "编辑器": [
    ["插件介绍", "/zhCN-docs/idea"],
    ["FAQ", "/zhCN-docs/idea/faq"],
    ["快捷键", "/zhCN-docs/idea/000-shortcut"],
    ["安装插件", "/zhCN-docs/idea/001-install-plugin"],
    ["启动项目", "/zhCN-docs/idea/002-start-project"],
    ["工具窗口", "/zhCN-docs/idea/003-tool-window"],
    ["服务", "/zhCN-docs/idea/004-service-api-collection"],
    ["API", "/zhCN-docs/idea/005-api-detail"],
    ["组件", "/zhCN-docs/idea/006-components"],
    ["常量", "/zhCN-docs/idea/007-constants"],
    ["错误", "/zhCN-docs/idea/008-errors"],
    ["实体", "/zhCN-docs/idea/009-entity"],
    ["Stub", "/zhCN-docs/idea/010-stub"],
    ["测试", "/zhCN-docs/idea/011-test"],
    ["服务设置", "/zhCN-docs/idea/012-settings-server"],
    ["导出设置", "/zhCN-docs/idea/013-settings-export"],
    ["知识库设置", "/zhCN-docs/idea/014-settings-knowledge"],
    ["编辑器", "/zhCN-docs/idea/015-editor"],
  ] as NavEntry[],
  "How-To": [
    ["文件上传", "/zhCN-docs/how/001_support_upload_file"],
    ["更新 Header 与 Cookie", "/zhCN-docs/how/002_update_header_cookie"],
    ["如何使用 Enum", "/zhCN-docs/how/003_how_to_handle_enum"],
    ["如何定义 API 根路径", "/zhCN-docs/how/004_how_define_api_root_path"],
    ["有用的内置小插件", "/zhCN-docs/how/005_helpful_inner_plugin"],
    ["理解 Max/Min/Length/Items", "/zhCN-docs/how/006_understand_max_min_length_items_properties"],
  ] as NavEntry[],
  Kola: [
    ["介绍", "/zhCN-docs/kola"],
    ["Kola 是什么", "/zhCN-docs/kola/001_what_is_kola"],
    ["Kola 设计", "/zhCN-docs/kola/002_design_of_kola"],
    ["Kola 协议", "/zhCN-docs/kola/003_dsl_contract"],
    ["Kola 原则", "/zhCN-docs/kola/004_principle"],
    ["工具链", "/zhCN-docs/kola/005_tool_chain"],
    ["配置与附录", "/zhCN-docs/kola/006_configurations"],
  ] as NavEntry[],
  "核心原则": [
    ["工程中的共情", "/zhCN-docs/principles/empathy-is-important"],
    ["共同语言", "/zhCN-docs/principles/common-language"],
    ["单一可信源", "/zhCN-docs/principles/single-source-of-truth"],
    ["借力集成", "/zhCN-docs/principles/leverage-integration"],
  ] as NavEntry[],
  "里程碑": [
    ["索引", "/zhCN-docs/milestone"],
    ["Milestone-1.0.0", "/zhCN-docs/milestone/milestone-1.0.0-RELEASE"],
    ["里程碑 2.0.0", "/zhCN-docs/milestone/milestone-2.0.0-RELEASE"],
    ["Upgrade-20250515", "/zhCN-docs/milestone/upgrade-1.3.8-RELEASE"],
    ["里程碑 20240510", "/zhCN-docs/milestone/milestone-20240510"],
    ["里程碑 20240222", "/zhCN-docs/milestone/milestone-20240222"],
  ] as NavEntry[],
  "更新日志": [
    ["索引", "/zhCN-docs/changelog"],
    ["SDK", "/zhCN-docs/changelog/sdk"],
    ["SDK 0.7.8", "/zhCN-docs/changelog/detail/SDK_0.7.8"],
    ["SDK 0.7.8 中文", "/zhCN-docs/changelog/detail/SDK_0.7.8_cn"],
    ["SDK 0.8.6", "/zhCN-docs/changelog/detail/SDK_0.8.6"],
    ["SDK 0.8.6 中文", "/zhCN-docs/changelog/detail/SDK_0.8.6_cn"],
    ["Plugin", "/zhCN-docs/changelog/plugin"],
  ] as NavEntry[],
};
